### ISSUE TITLE
Screenshot with datapoints

### ISSUE THREAD

**Issue by shmuel-krakower** [bhattchaitanya/Grafana-Dashboard-Generator#1]
Hi
Would you update the example screenshot with some data? Would be easier to get understanding of what that tool output looks like.

**Comment by bhattchaitanya** [comment]
Thanks a ton for the feedback. I realized critical dashboard defects while attempting to get the screenshot. I have fixed it in v1.1
The wiki and read me document is also fixed in V1.1.
